### ISSUE TITLE
Addicted not working

### ISSUE THREAD

**Issue by alexjoni** [sahilgupta/pysubd#4]
Mostly for TV Series.
When a TV Series is identified (SxxEyy) Addic7ed is queried, which most of the time fails with 
"Searching Addic7ed.com for Foo.S02E04.HDTV.x264.mkv
No active Internet connection found. Kindly check and try again."
After that Opensubtitles is not queried anymore.
If I rename the show to 204 instead of S02E04 it tried Opensubtitles directly and succeeds.
Would you be able to provide a switch to disable the Addic7ed check altogether? Preferably as a windows executable...

**Comment by nemo81** [comment]
Same issue here unfortunately..

**Comment by sahilgupta** [comment]
@alexjoni , Thanks for reporting this. I'll have a look at this soon.
